# Generated by Django 6.0.3 on 2026-04-01 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_tenant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('MPESA', 'M-Pesa Payment'), ('CHARGE', 'Monthly Rent Charge'), ('MANUAL', 'Manual Adjustment')], default='MPESA', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
