# Generated by Django 6.0.3 on 2026-04-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_payment_transaction_type_property_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
