# Generated by Django 6.0.3 on 2026-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_unit_monthly_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='garbage_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_garbage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_service_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_water_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='service_charge_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
