# Generated by Django 6.0.3 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='previous_water_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
