# Generated by Django 6.0.3 on 2026-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_unit_previous_water_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='garbage_billing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garbage_fee_default',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='water_billing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
