import africastalking
import logging
import pytz
from fpdf import FPDF
from io import BytesIO
from datetime import timedelta
from django.utils import timezone

# --- SMS Configuration ---
username = "sandbox" 
api_key = "YOUR_AT_API_KEY_HERE" 
africastalking.initialize(username, api_key)
sms = africastalking.SMS
logger = logging.getLogger(__name__)

def send_payment_confirmation(tenant, amount):
    """Sends a professional SMS to the tenant once payment is confirmed."""
    phone = tenant.phone_number
    if not phone.startswith('+'):
        phone = f"+254{phone.lstrip('0')}"

    message = (
        f"Hello {tenant.name}, payment of KES {amount} received for Unit {tenant.unit.house_number}. "
        f"Your new balance is KES {tenant.balance}. Thank you!"
    )

    try:
        response = sms.send(message, [phone])
        logger.info(f"SMS Sent to {tenant.name}: {response}")
        return response
    except Exception as e:
        logger.error(f"SMS Failed for {tenant.name}: {str(e)}")
        return None

def send_invoice_notification(tenant, rent_amount, month_name):
    """Sends an SMS alert when a new monthly rent charge is generated."""
    phone = tenant.phone_number
    if not phone.startswith('+'):
        phone = f"+254{phone.lstrip('0')}"

    message = (
        f"Hello {tenant.name}, your rent for {month_name} of KES {rent_amount} has been invoiced. "
        f"Your new balance is KES {tenant.balance}. Please pay via the Ke-Rental portal."
    )

    try:
        response = sms.send(message, [phone])
        logger.info(f"Invoice SMS Sent to {tenant.name}: {response}")
        return response
    except Exception as e:
        logger.error(f"Invoice SMS Failed for {tenant.name}: {str(e)}")
        return None

# --- PDF Generation Logic ---

class ReceiptPDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, 'Generated by Ke-Rental System - 2026', 0, 0, 'C')

def generate_receipt_pdf(payment):
    """Generates a PDF with Outstanding Balance for Receipts and Periods for Invoices."""
    pdf = ReceiptPDF()
    pdf.add_page()
    
    # --- TIMEZONE CORRECTION ---
    # Convert UTC database time to Nairobi Local Time
    nairobi_tz = pytz.timezone('Africa/Nairobi')
    local_time = payment.date_created.astimezone(nairobi_tz)
    
    is_payment = payment.transaction_type == 'MPESA'
    
    # 1. HEADER BRANDING
    pdf.set_font("helvetica", 'B', 16)
    if is_payment:
        pdf.set_text_color(25, 135, 84) # Green for Receipts
        pdf.cell(0, 10, "PAYMENT RECEIPT", 0, 1, 'R')
    else:
        pdf.set_text_color(111, 66, 193) # Purple for Invoices
        pdf.cell(0, 10, "RENT INVOICE", 0, 1, 'R')
    
    pdf.set_text_color(0, 0, 0) # Reset to black
    pdf.ln(5)

    # Property Info
    pdf.set_font("helvetica", 'B', 12)
    pdf.cell(0, 10, f"Property: {payment.tenant.unit.property.name}", 0, 1)
    pdf.set_font("helvetica", size=11)
    pdf.cell(0, 8, f"Location: {payment.tenant.unit.property.location}", 0, 1)
    
    # Billing Period for Invoices
    if not is_payment:
        start_date = (local_time - timedelta(days=30)).strftime('%d %b %Y')
        end_date = local_time.strftime('%d %b %Y')
        pdf.set_font("helvetica", 'I', 10)
        pdf.cell(0, 8, f"Billing Period: {start_date} to {end_date}", 0, 1)
    
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y()+2, 200, pdf.get_y()+2)
    pdf.ln(10)
    
    # Transaction Details
    pdf.set_font("helvetica", 'B', 11)
    label = "Receipt No:" if is_payment else "Invoice No:"
    pdf.cell(40, 8, label)
    pdf.set_font("helvetica", size=11)
    pdf.cell(0, 8, f"{payment.mpesa_receipt or 'INV-' + str(payment.id)}", 0, 1)
    
    pdf.set_font("helvetica", 'B', 11)
    pdf.cell(40, 8, "Date:")
    pdf.set_font("helvetica", size=11)
    # Using the local_time variable instead of raw date_created
    pdf.cell(0, 8, f"{local_time.strftime('%d %b %Y, %H:%M')}", 0, 1)

    pdf.set_font("helvetica", 'B', 11)
    pdf.cell(40, 8, "Tenant:")
    pdf.set_font("helvetica", size=11)
    pdf.cell(0, 8, f"{payment.tenant.name} (Unit: {payment.tenant.unit.house_number})", 0, 1)
    pdf.ln(10)

    # 2. THE TABLE
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("helvetica", 'B', 11)
    pdf.cell(140, 10, "Description", 1, 0, 'L', fill=True)
    pdf.cell(50, 10, "Amount (KES)", 1, 1, 'R', fill=True)

    pdf.set_font("helvetica", size=11)
    
    # Find relevant breakdown
    breakdown_note = payment.note
    if not breakdown_note and is_payment:
        from .models import Payment
        latest_charge = Payment.objects.filter(
            tenant=payment.tenant, 
            transaction_type='CHARGE'
        ).order_by('-date_created').first()
        if latest_charge:
            breakdown_note = latest_charge.note

    if breakdown_note:
        items = breakdown_note.split(', ')
        for item in items:
            if ':' in item:
                desc, amt = item.split(': ')
                pdf.cell(140, 10, f"  {desc}", 1)
                pdf.cell(50, 10, amt, 1, 1, 'R')
    else:
        pdf.cell(140, 10, f"  {payment.get_transaction_type_display()}", 1)
        pdf.cell(50, 10, f"{payment.amount}", 1, 1, 'R')

    # 3. TOTAL BOX
    pdf.ln(2)
    pdf.set_font("helvetica", 'B', 12)
    pdf.cell(140, 12, "TOTAL PAID" if is_payment else "TOTAL DUE", 1, 0, 'R')
    
    if is_payment:
        pdf.set_fill_color(218, 247, 227) # Light Green
    else:
        pdf.set_fill_color(238, 232, 249) # Light Purple
        
    pdf.cell(50, 12, f"KES {payment.amount}", 1, 1, 'R', fill=True)

    # 4. STATUS & BALANCE FOOTER
    pdf.ln(10)
    if is_payment:
        pdf.set_font("helvetica", 'B', 11)
        pdf.set_text_color(220, 53, 69) # Bootstrap Danger Red
        pdf.cell(0, 10, f"OUTSTANDING BALANCE: KES {payment.tenant.balance}", 0, 1, 'R')
        pdf.set_text_color(25, 135, 84) # Reset to Green
        pdf.cell(0, 10, "STATUS: PAID & CONFIRMED", 0, 1, 'C')
    else:
        pdf.set_text_color(111, 66, 193) # Purple
        pdf.cell(0, 10, "STATUS: OUTSTANDING", 0, 1, 'C')

    return pdf.output()