import africastalking
import logging
from fpdf import FPDF
from io import BytesIO

# --- SMS Configuration ---
username = "sandbox" 
api_key = "YOUR_AT_API_KEY_HERE" 
africastalking.initialize(username, api_key)
sms = africastalking.SMS
logger = logging.getLogger(__name__)

def send_payment_confirmation(tenant, amount):
    """Sends a professional SMS to the tenant once payment is confirmed."""
    phone = tenant.phone_number
    if not phone.startswith('+'):
        phone = f"+254{phone.lstrip('0')}"

    message = (
        f"Hello {tenant.name}, payment of KES {amount} received for Unit {tenant.unit.house_number}. "
        f"Your new balance is KES {tenant.balance}. Thank you!"
    )

    try:
        response = sms.send(message, [phone])
        logger.info(f"SMS Sent to {tenant.name}: {response}")
        return response
    except Exception as e:
        logger.error(f"SMS Failed for {tenant.name}: {str(e)}")
        return None

# --- PDF Generation Logic ---

class ReceiptPDF(FPDF):
    def header(self):
        # Using helvetica as it's a standard core font
        self.set_font('helvetica', 'B', 15)
        self.cell(0, 10, 'KE-RENTAL OFFICIAL RECEIPT', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, 'Generated by Ke-Rental System - April 2026', 0, 0, 'C')

def generate_receipt_pdf(payment):
    """Generates a raw PDF byte stream for a specific payment."""
    pdf = ReceiptPDF()
    pdf.add_page()
    
    # Property Info
    pdf.set_font("helvetica", 'B', 12)
    pdf.cell(0, 10, f"Property: {payment.tenant.unit.property.name}", 0, 1)
    pdf.set_font("helvetica", size=11)
    pdf.cell(0, 8, f"Location: {payment.tenant.unit.property.location}", 0, 1)
    pdf.ln(5)

    # Horizontal Line
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Transaction Details
    pdf.cell(0, 8, f"Receipt No: {payment.mpesa_receipt or 'N/A'}", 0, 1)
    pdf.cell(0, 8, f"Date: {payment.date_created.strftime('%d %b %Y, %H:%M')}", 0, 1)
    pdf.cell(0, 8, f"Tenant: {payment.tenant.name}", 0, 1)
    pdf.cell(0, 8, f"Unit: {payment.tenant.unit.house_number}", 0, 1)
    pdf.ln(10)

    # Highlighted Amount Paid
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("helvetica", 'B', 16)
    pdf.cell(0, 20, f"TOTAL PAID: KES {payment.amount}", 1, 1, 'C', fill=True)
    pdf.ln(10)

    # Financial Summary
    pdf.set_font("helvetica", size=11)
    pdf.cell(0, 8, f"Current Outstanding Balance: KES {payment.tenant.balance}", 0, 1)
    
    # Return as raw bytes
    return pdf.output()